/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
 
import model.PecasBean;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PecasDAO;
import model.UsuarioDAO;
 
public class Inicio extends javax.swing.JFrame {
    DefaultTableModel model;
    PecasDAO dao = new PecasDAO();
 
    public Inicio() {
        initComponents();
        OcuparTabela();
        configurarTabelaAcoes();
    }
 
  public void OcuparTabela() {
    // Sobrescrevemos o isCellEditable para retornar false em todas as células
    model = new DefaultTableModel(
        new Object [][] {},
        new String [] {"id", "cod", "nome", "cod orgnl", "quantidade"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Torna a tabela não editável
        }
    };
    
    tbl.setModel(model); // Define o novo modelo na tabela
    model.setRowCount(0);
    
    List<PecasBean> lista = dao.listarpecas();
    for (PecasBean u : lista) {
        model.addRow(new Object[]{
            u.getId(),
            u.getCod(),
            u.getNome(),
            u.getCod_orgnl(),
            u.getQntde()
        });
    }
}
  
  
 
    private void configurarTabelaAcoes() {
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    editarPecaSelecionada();
                }
            }
        });
    }
 
    private void editarPecaSelecionada() {
    int linhaSelecionada = tbl.getSelectedRow();
    if (linhaSelecionada == -1) return;

    // pega dados da linha selecionada
    int id      = (int) model.getValueAt(linhaSelecionada, 0);
    int cod     = (int) model.getValueAt(linhaSelecionada, 1);
    String nomeItem = (String) model.getValueAt(linhaSelecionada, 2);
    String codOrgnl = (String) model.getValueAt(linhaSelecionada, 3);
    int qntdeItem   = (int) model.getValueAt(linhaSelecionada, 4);

    PecasBean peca = new PecasBean(id, nomeItem, cod, codOrgnl, qntdeItem);
    
   
    Mudanca form = new Mudanca();
    form.mostrarFormularioEdicao(peca);
    form.setVisible(true);
    
    // Fecha a tela Inicio
    this.dispose(); 
}
 
    private void deletarPecaSelecionada() {
        int linhaSelecionada = tbl.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma peça para deletar", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        int id   = (int) model.getValueAt(linhaSelecionada, 0);
        String nome = (String) model.getValueAt(linhaSelecionada, 2);
 
        int confirmacao = JOptionPane.showConfirmDialog(
            this,
            "Deseja deletar a peça \"" + nome + "\"?",
            "Confirmar exclusão",
            JOptionPane.YES_NO_OPTION
        );
 
        if (confirmacao == JOptionPane.YES_OPTION) {
            dao.deletar(id);
            OcuparTabela(); // atualiza a tabela
            JOptionPane.showMessageDialog(this, "Peça deletada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void acessarrComAutenticacao() {
        javax.swing.JTextField txtUsuario = new javax.swing.JTextField();
        javax.swing.JPasswordField txtSenha = new javax.swing.JPasswordField();
        Object[] message = {
            "Usuário:", txtUsuario,
            "Senha:", txtSenha
        };

        int opcao = JOptionPane.showConfirmDialog(
            this, message, "Login Admin Requerido", JOptionPane.OK_CANCEL_OPTION
        );

        if (opcao == JOptionPane.OK_OPTION) {
            String user = txtUsuario.getText().trim();
            String pass = new String(txtSenha.getPassword()).trim();

            if (user.isEmpty() || pass.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha usuário e senha.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (dao.validarAdmin(user, pass)) {
                new Cadastro().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Acesso negado: usuário incorreto ou sem permissão de admin.", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        entrada = new javax.swing.JButton();
        saida = new javax.swing.JButton();
        cadauser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("inicio");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "cod", "nome", "cod orgnl", "quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("deseja ir para:");

        entrada.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        entrada.setText("entrada");
        entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaActionPerformed(evt);
            }
        });

        saida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saida.setText("saida");
        saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaActionPerformed(evt);
            }
        });

        cadauser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadauser.setText("cadastrar usuario");
        cadauser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadauserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(entrada)
                .addGap(88, 88, 88)
                .addComponent(saida, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadauser)
                .addGap(98, 98, 98))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saida)
                    .addComponent(cadauser))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaActionPerformed
        // TODO add your handling code here:
        new Entrada().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_entradaActionPerformed

    private void saidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaActionPerformed
        // TODO add your handling code here:
        new Saida().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_saidaActionPerformed

    private void cadauserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadauserActionPerformed
        // TODO add your handling code here:
        acessarrComAutenticacao();
    }//GEN-LAST:event_cadauserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadauser;
    private javax.swing.JButton entrada;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saida;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
